name: tiff_fax_format_examples
description: Some TIFF fax format examples using 'image' library (from Brendan-Duncan https://github.com/brendan-duncan)
homepage: https://github.com/johann-blanchet/tiff_fax_format_examples

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image: ^3.1.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/
    # - assets/images/
    - assets/images/image-broken.png
    - assets/images/test-fax-format.tiff
    - assets/images/test-fax-format-multipages.tiff

